services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8091:8080"
    networks:
      - backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - backend
      - frontend
    volumes:
      - ./api:/app

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "8090:5000"
    depends_on:
      - api
      - database
    volumes:
      - ./web-app:/app
    networks:
      - frontend




volumes:
  db-data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
